import { useMemo, useState } from "react";
import "./App.css";

function removeThinkTags(text: string) {
  return text
    .replace(/<think>[\s\S]*?<\/think>/gi, "")
    .replace(/<think>[\s\S]*/gi, "")
    .trim();
}

function App() {
  const [message, setMessage] = useState("");
  const [answer, setAnswer] = useState("");
  const [rawAnswer, setRawAnswer] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const displayAnswer = useMemo(() => {
    return removeThinkTags(rawAnswer || answer);
  }, [rawAnswer, answer]);

  async function sendMessage() {
    setLoading(true);
    setError("");
    setAnswer("");
    setRawAnswer("");

    try {
      const response = await fetch("http://localhost:4000/api/agent/stream", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message }),
      });

      if (!response.ok || !response.body) {
        throw new Error("Streaming request failed");
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();

      let buffer = "";
      let accumulated = "";

      while (true) {
        const { value, done } = await reader.read();

        if (done) {
          break;
        }

        buffer += decoder.decode(value, { stream: true });

        const chunks = buffer.split("\n\n");
        buffer = chunks.pop() || "";

        for (const chunk of chunks) {
          const eventLine = chunk
            .split("\n")
            .find((line) => line.startsWith("event:"));
          const dataLine = chunk
            .split("\n")
            .find((line) => line.startsWith("data:"));

          if (!eventLine || !dataLine) {
            continue;
          }

          const event = eventLine.replace("event:", "").trim();
          const data = JSON.parse(dataLine.replace("data:", "").trim());

          if (event === "token") {
            accumulated += data.token;
            setRawAnswer(accumulated);
            setAnswer(removeThinkTags(accumulated));
          }

          if (event === "done") {
            setLoading(false);
          }

          if (event === "error") {
            throw new Error(data.message || "Unknown streaming error");
          }
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
      setLoading(false);
    }
  }

  return (
    <main className="app-shell">
      <section className="hero">
        <h1>mimOE Local Agent</h1>
        <p>
          A small full-stack AI agent connected to a local mimOE
          OpenAI-compatible inference endpoint using raw fetch.
        </p>
      </section>

      <section className="workbench">
        <div className="prompt-card">
          <div className="section-header">
            <div className="section-content">
              <h2>Prompt</h2>
              <p>Ask the local model a question or trigger a simple tool.</p>
            </div>
          </div>

          <textarea
            value={message}
            onChange={(event) => setMessage(event.target.value)}
            rows={6}
            placeholder="Ask the local agent something..."
          />

          <div className="actions">
            <button onClick={sendMessage} disabled={loading || !message.trim()}>
              {loading ? "Thinking..." : "Send"}
            </button>
          </div>

          {error && <div className="error-banner">{error}</div>}
        </div>

        {(displayAnswer || loading) && (
          <div className="answer-card">
            <div className="section-header">
              <div className="section-content">
                <h2>Answer</h2>
                <p>Generated by the local mimOE model.</p>
              </div>
            </div>

            <div className="answer-content">
              {displayAnswer || <span className="muted">Waiting...</span>}
              {loading && <span className="cursor">▍</span>}
            </div>
          </div>
        )}
      </section>
    </main>
  );
}

export default App;
